version: 0.0
os: linux
hooks:
  BeforeInstall:
  - location: script.sh
    timeout: 300
    runas: root
  AfterInstall:
  - location: script.sh
    timeout: 300
    runas: root
  ApplicationStart:
  - location: script.sh
    timeout: 300
    runas: root
  ApplicationStop:
  - location: script.sh
    timeout: 300
    runas: root





