version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - gradle assemble
      - gradle bootjar

artifacts:
  discard-paths: yes
  files:
    - webWonders/build/libs/webWonders-0.0.1-SNAPSHOT.jar
